const String externalIssueLabel = "GhReporter-external";
const String internalIssueLabel = "GhReporter-internal";
const String fromGhReporterPackage = "Reported by GhReporter Package";
const String bugLabel = "bug";
const String bodyTitle = "title";
const String bodyBody = "body";
const String ownerBody = "owner";
const String repoBody = "repo";
const String dateBody = "date";
