const String externalIssueLabel = "GhSnitch-external";
const String internalIssueLabel = "GhSnitch-internal";
const String fromGhRSnitchPackage = "Reported by GhSnitch Package";
const String bugLabel = "bug";
const String bodyTitle = "title";
const String bodyBody = "body";
const String ownerBody = "owner";
const String repoBody = "repo";
const String dateBody = "date";
